name 'jboss'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures jboss-cookbook'
long_description 'Installs/Configures jboss-cookbook'
version '0.1.0'

depends 'poise'
depends 'java'
depends 'poise-service'
