name 'poise-jboss'
maintainer 'Luis Felipe Moura Pereira De Siqueira'
maintainer_email 'LouTheBrew@gmail.com'
license 'MIT'
description 'resources for controlling jboss'
long_description 'resources for controlling jboss'
version '0.0.4'

depends 'poise'
depends 'poise-service'
depends 'poise-fpm'
depends 'poise-s3'
depends 'java'
